name: Solve

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  solve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Solve the puzzle
      run: |
        python solve.py
